import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import PianoImg from '../images/piano.jpg'

export default function Home() {
  return (
    <div className='min-h-screen font-mono text-gray-800'>
      <Head>
        <title>Azeriru's Music Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */ }
      <Header />
      <div className='md:flex px-5 md:px-10'>
        <div className='flex md:hidden relative w-full h-[20vh] mt-3 rounded-md overflow-hidden shadow-md'>
          <Image className='object-cover' layout='fill' objectPosition='center' src={ PianoImg } alt='heroimg' />

        </div>
        <div className='lg:max-w-6xl pt-10 md:pt-40'>

          <h1 className='text-lg md:text-2xl mb-5'>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa, ducimus.
          </h1>
          <p className='max-w-sm text-xs md:text-sm'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laborum qui quibusdam tenetur expedita magni officiis tempora, alias consequuntur eligendi similique?</p>
        </div>
        <div className='hidden md:flex relative w-full lg:w-[50%] h-[90vh] mt-3 rounded-md overflow-hidden shadow-md'>
          <Image className='object-cover' layout='fill' objectPosition='center' src={ PianoImg } alt='heroimg' />

        </div>
      </div>

    </div>
  )
}
