import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import HeroImage from '../components/HeroImage'

export default function Home() {
  return (
    <div className='min-h-screen font-mono text-gray-800'>
      <Head>
        <title>Azeriru's Music Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */ }
      <Header />
      <div className='md:flex px-5 md:px-10 pt-40'>
        <div className='max-w-xl'>

          <h1 className='text-lg md:text-2xl mb-5'>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa, ducimus.
          </h1>
          <p className='max-w-sm text-xs md:text-sm'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laborum qui quibusdam tenetur expedita magni officiis tempora, alias consequuntur eligendi similique?</p>
        </div>
        <div>
          Hello
        </div>
      </div>

    </div>
  )
}
